import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
    // Base public path
    base: './',

    // Build configuration
    build: {
        // Output directory
        outDir: 'dist',

        // Assets directory inside outDir
        assetsDir: 'assets',

        // Generate source maps for debugging
        sourcemap: true,

        // Rollup options
        rollupOptions: {
            input: {
                // Main entry point (CSS linked separately in HTML when cssCodeSplit: false)
                main: resolve(__dirname, 'js/modules/index.js')
            },
            output: {
                // Entry file naming
                entryFileNames: 'js/[name].[hash].js',
                // Chunk file naming
                chunkFileNames: 'js/chunks/[name].[hash].js',
                // Asset file naming
                assetFileNames: (assetInfo) => {
                    if (assetInfo.name.endsWith('.css')) {
                        return 'css/[name].[hash][extname]';
                    }
                    return 'assets/[name].[hash][extname]';
                },
                // Manual chunks for better caching
                manualChunks: {
                    // Core modules
                    'chatbot-core': [
                        './js/modules/config.js',
                        './js/modules/state.js',
                        './js/modules/i18n.js'
                    ],
                    // UI modules
                    'chatbot-ui': [
                        './js/modules/messages.js',
                        './js/modules/ui.js'
                    ],
                    // API & Upload
                    'chatbot-api': [
                        './js/modules/api.js',
                        './js/modules/upload.js',
                        './js/modules/analytics.js'
                    ]
                }
            }
        },

        // Minification
        minify: 'terser',
        terserOptions: {
            compress: {
                drop_console: true,
                drop_debugger: true
            }
        },

        // CSS configuration
        cssCodeSplit: false,
        cssMinify: true
    },

    // Development server
    server: {
        port: 3000,
        open: true,
        cors: true,
        proxy: {
            // Proxy PHP API requests to MAMP
            '/php': {
                target: 'http://localhost:8888/hunyuanocr/visa-chatbot',
                changeOrigin: true
            }
        }
    },

    // Preview server (production build preview)
    preview: {
        port: 4173
    },

    // Resolve configuration
    resolve: {
        alias: {
            '@': resolve(__dirname, 'js'),
            '@modules': resolve(__dirname, 'js/modules'),
            '@css': resolve(__dirname, 'css')
        }
    },

    // Plugins
    plugins: [
        // Custom plugin to handle PHP integration
        {
            name: 'vite-php-manifest',
            generateBundle(options, bundle) {
                // Generate a PHP-readable manifest
                const manifest = {};
                for (const [fileName, chunk] of Object.entries(bundle)) {
                    if (chunk.type === 'chunk' && chunk.isEntry) {
                        manifest[chunk.name] = {
                            file: fileName,
                            css: chunk.viteMetadata?.importedCss || []
                        };
                    }
                    if (chunk.type === 'asset' && chunk.name?.endsWith('.css')) {
                        manifest['styles'] = {
                            file: fileName
                        };
                    }
                }

                // Emit PHP manifest file
                this.emitFile({
                    type: 'asset',
                    fileName: 'manifest.php',
                    source: `<?php\n// Auto-generated by Vite\nreturn ${JSON.stringify(manifest, null, 2).replace(/"/g, "'").replace(/{/g, '[').replace(/}/g, ']').replace(/:/g, ' =>')};\n`
                });
            }
        }
    ],

    // Define global constants
    define: {
        __APP_VERSION__: JSON.stringify('4.0.0'),
        __BUILD_TIME__: JSON.stringify(new Date().toISOString())
    },

    // Optimize dependencies
    optimizeDeps: {
        include: [],
        exclude: []
    }
});
